### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by KMStacker** [tuheli/ot-harjoitustyo#1]
Projektin lataushetki:    10/12/2024    14:46 ja 15:43

Aluksi en saanut ohjelmaa toimimaan ja aikani kokeiltua menin takaisin githubiin ja totesin, että sinne repositorioon on juuri tullut uusia committeja. Latasin projektin uudestaan ja sitten alkoi hommat toimia. (Sen vuoksi myös kaksi eri latausaikaa.)

Pelissä on mielenkiintoinen idea ja se on saatu myös toteutettua mielestäni melko hyvin jo tähän mennessä, vaikka hieman vaikuttaakin siltä, että tekeminen on vielä sillä tavoin kesken, ettei ohjelmaa ole yritettykään vielä viimeistellä lopulliseen kiiltoonsa. Vaikka siis pelin ulkoasu onkin jo esimerkiksi värimaailmaltaan hyvin onnistunut ja vaikuttaa tarkkaan mietityltä.

Pelin käynnistämiseen ja muihin asioihin on annettu hyvät ja mielestäni täysin riittävät ohjeet READMEssä, tosin näin windows-käyttäjänä tasks tiedostoon piti tehdä muutoksia, jotta “poetry run invoke” -komennot alkoivat toimia (kurssin vaatimuksena linuxilla toimiminen, joten windows-jutut voinee unohtaa!).

Peli sekä editori käynnistyivät ongelmitta. Peli aukeaa valintaikkunaan, jossa valittavana on 4 eri tasoa, joita klikkaamalla peli alkaa välittömästi. Peli alkaa automaattisesti uudestaan, jos pelissä törmää laatikoihin, ja jatkuu niin pitkään kunnes ikkuna suljetaan tai painetaan ESC-näppäintä, jolloin palataan takaisin tason valitsemiseen. Edellä mainittu ei ehkä optimikäyttäytymistä, mutta siihen lienee tulossa muutos jatkossa. Editorissa taas pystyy lisäämään laatikoita kenttään hiiren vasemman näppäimen klikkauksella ja poistamaan oikean näppäimen klikkauksella. Editorin toiminta jäi sellaisenaan hieman irralliseksi, mutta siihenkin löytyy varmasti jatkossa selitys, että mitä sillä halutaan tuoda käyttäjälle.

Eri pelin tasoja kokeiltuani ja projektia tutkittuani en päässyt selvyyteen, että oliko tason valitsemisella jotain merkitystä itse peliin, mutta alin taso saattoi tuntua aavistuksen hitaammalta kuin ylin taso. Parannusehdotuksena voisinkin tähän liittyen mainita selkeämmät erot eri tasojen välillä, jotta jokaiselle löytyisi jokin mieluisa taso. 
En myöskään huomannut pelissä olevan vielä näkyvissä laskuria yritysten määrästä eri tasoilla, mutta koodista kyllä löytyi viitteitä laskurista, joten eiköhän sekin ilmesty näkyville ohjelmaan tulevaisuudessa!

Editorin kokeilun myötä parannusehdotuksena tuli mieleen, että editoitavana olevasta kentästä saisi paremman yleiskuvan, jos kenttää pystyisi zoomaamaan (+/-) tai jos editoitavana olevassa kentässä voisi likkua ilman että oranssi neliö olisi sidottuna ainoastaan ruudun alalaitaan.

Testejä näytti olevan tässä vaiheessa vielä melko vähän (3 kpl), mutta olemassa olevat testit menivät komeasti läpi. Testikattavuusraporttikin kertoo samanlaista tarinaa siitä, että vielä olisi paljon eri osa-alueita katettavana testeillä (ja varmasti niitä testejäkin alkaa ilmestyä lisää sitä mukaa kun ohjelma etenee ja kehittyy).  

Pylintin ajo antoi koodeille arvosanaksi 5.26/10, joten koodin hienosäädössä lienee vielä myös tekemistä. Tosin ohjelma vaikuttaa olevan sellaisessa vaiheessa, että testeihin ja koodin muotoseikkoihin ei ole vielä ehditty juurikaan kiinnittää huomiota (ainakaan pylint-mielessä), mikä on mielestäni hyvinkin ymmärrettävää. 

Ohjelma on jaettu useaan eri tiedostoon, jotka on nimetty kuvaavasti, joten mielestäni ohjelman rakenne on ainakin siinä mielessä selkeästi toteutettu. 

Kaiken kaikkiaan peli vaikuttaa oikein mielenkiintoiselta tapaukselta niin perusidealtaan kuin toteutukseltaankin editoreineen ja tason valitsemisineen. Peli vaikuttaisi olevan tässä vaiheessa jo perus toiminnallisuuksiltaan sen verran pitkällä, ettei valmiiseen peliin tuntuisi olevan enää pitkä matka, joten…

... Tsemppiä vaan loppurutistukseen, hyvä siitä tulee!!

**Comment by tuheli** [comment]
Kiitos katselmoinnista! :)

Oli juu vähän vaiheessa katselmointia varten, mutta aika hyvä tuuri näköjään kävi, kun sopivia committeja sattui tulemaan samaan aikaan kun tsekkasit :D!
